name: Merge EPG with Logos

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install requests

    - name: Run merge script
      run: python merge_epg_with_logos.py

    - name: Upload merged EPG
      uses: actions/upload-artifact@v4
      with:
        name: epg_with_logos
        path: epg_with_logos.xml
