name: Merge EPG with Logos

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run merge script
      run: python merge_epg_with_logos.py

    - name: Upload merged EPG
      uses: actions/upload-artifact@v3
      with:
        name: epg_with_logos
        path: epg_with_logos.xml
